import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/Providers";
import { Toaster } from "@/components/ui/toaster";
import { CookiesProvider } from "next-client-cookies/server";
import { Inter } from "next/font/google";
import HeaderWrapper from "@/components/HeaderWrapper/HeaderWrapper";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-slate-100`}>
        <Providers>
          <CookiesProvider>
            <HeaderWrapper>
              <Header />
            </HeaderWrapper>
            {children}
          </CookiesProvider>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
